orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2




jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: 
          name: Run tests with coverage
          command: npm test --coverage
      - run:
          name : compile
          command : npm run compile
      - run:
          name: Deploy application
          command: sls deploy --stage pre

workflows:
  version: 2
  build-andtest-project:
    jobs:
      - build
      - test:
          requires:
          - build
