version: 2.1

jobs:
    dependencies-zip-generation:
        docker:
            - image: node:12.20.1-stretch-slim
        steps:
            - checkout
            - run:
                name: install node modules
                command: npm install
            - run:
                name: Install zip
                command: |
                    apt-get update
                    apt-get install zip -y
            - run:
                name: compile
                command: npm run compile
            - run:
                name: zip and save source code
                command: zip -r function.zip built/* node_modules
            - persist_to_workspace:
                root: ./
                paths: 
                    - function.zip
    deploy-lambda:
        docker:
            - image: hashicorp/terraform:light
        steps:
            - checkout
            - run: echo $aws_secret_access_key
            - attach_workspace:
                at: ./Terraform
            - run:
                name: Terraform init
                command: |
                    cd Terraform &&
                    terraform init
            - run: ls
            - run:
                name: Terraform destroy
                command: |
                    cd Terraform &&
                    terraform destroy -auto-approve
            - run:
                name: Terraform provide and deploy
                command: |
                    cd Terraform &&
                    terraform apply -auto-approve
workflows:
    main:
        jobs:
            - dependencies-zip-generation
            - deploy-lambda:
                context: 
                    - AWSContext
                requires: 
                    - dependencies-zip-generation
